dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -pass pass:$ENC_PWD -in secring.gpg.enc -out local.secring.gpg -d
- openssl aes-256-cbc -pass pass:$ENC_PWD -in pubring.gpg.enc -out local.pubring.gpg -d
- gpg --import local.secring.gpg
- gpg --import local.pubring.gpg

after_install:
- rm local.pubring.gpg
- rm local.secring.gpg

after_success:
- mvn clean -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID test jacoco:report coveralls:report

deploy:
  provider: releases
  api_key:
    secure: MzAZ4niPBXltGCUoszrm7cILD37IgMtg9omoKsWv8IHJ3aTGdBTJ4M97jw9+sgJEIRnUtal95DqOB4McuG9ziQb4kYWNH8WuUQJPxkWQs7mULj3KZHgs0I+ofV+p6x0trAy7zfiG9/eSsL46jYKUxawuSlF7vtU0EfRhHOwtceogpDu8F/AmfqbYCy1vT7/0fivMzXTNrIxVYeiYsFlTv8+B+cW0mHF3MWv1B5Xi7q9ElHhK6tlUaSvfaEVOmQ/3LWzIldG+lhzIrIpflHkG2dlI3DdoSp+CTGJXAiMXFhJbR/sRrsI8LO/G7T/4no++ST0Ny33ZdinG48MOL+ixhZtgEAEtiGroGwOKbnJ1ZK4A1O7SKNIbrdAHVFBpJjDvgqD34rbZcdGtU4MHp/ryWinqzPldD5m+qfTRkwj8Pc7/HEje6ksu2ENlsUCqzid2pfyyQo+ytsdmHozpEaeV6J0XBV++KAnh0gsPSBBTdq6f15XKbBfrKNgzCmK/4rx44NwrV0cHUphvT32HQ2ntvcYkzeoanxL6hLPfOai454VbFeFAneUMLrgNi5QOZd6zxUo9bWlV6d7Y+dF9MfpwbTvTkiU6AGsoPGUBJffzXQfZUFu45pCxnRRMER3/YVE5UtQ4c5r937yKN07IBQlGa2A7i+ms1S5vrMdxhQDuDe4=
  file:
  - target/mochatemplate-0.0.6.jar
  - target/mochatemplate-0.0.6-javadoc.jar
  - target/mochatemplate-0.0.6-sources.jar
  on:
    tags: true
before_deploy:
- mvn install generate-sources javadoc:jar
after_deploy:
- mvn deploy --settings deploy-settings.xml
env:
  global:
  - secure: WeKQuVgPNwr6+rgHFyTQ0B102sDiwcQkLpU9L1ovdpLBeFtu8eKelx9mJ7Ddp9HySV8RW/jmFwO8yQOD9H7ZFuxZxbtHqaoAisoMrsMxDj/SWZwCfSwkKNWT8R/l2JwZZ7ilVJ3fWWfOOn0vIVuvowBVtviteemyTxoDk7zGeMBW11hGLBRAhlmnnernW1dceV+WXOKipsmHPDdJtH3KX7HfICorq7/ATfXPGpekfPSa2EGrsWsOH7OiFmqwmClxUl2mJSy7vlwhm5uh3+cyzzUyY5cSf9SF3jiuZypWOBKTIKq9zE5w/5X/CD9gikEpYadGBvvuaGtUD5PraX0K7QV1cDge2IJthpffGoP4653z0FEcWEhXsINJFxnzLmnpacNm6Y9YlSzZnuUxhY9TBs7A6Ds53qx5iRHyNjYGXBjZ8qTtC9CzSt4lUGf4qyr/VCETuVVEANUfFebYjWNIXHKko43W2rds6fSnZ2rUnPvoK/pExPuhdh16UBGbi0FDoRfwamPz5aLtKUjzkbrEqH5vk0IyPkHL1jQ7soyqpz1sjnMBsxcwIqQEVKpKfu8vGhdmRur97kqUOcWmfrSktUjo5TM0TQzu2uwKyNTIY6eAIyzKdEVuNQIHI9PYtCCqXhd/z/TNGeYYkuTE9Tb2gCXAmAbNmQePP3BZ938t5nY=
  - secure: YPj0MCMeAI2PgrpVKIiYhFWFLJGhd/TB6oFa3LSWpk+QC0QQ+3H2p4GHhpDxOEPPgJnvs6j2pNNmth0nVn2mRXNuevgF5P4hZBS0UrKlq5my8ofypp4iWqF8EzknURt6MBAExxfMABU2OgCCGGucpXn4FfUooxyit5Ttj8OpvF81AvDwX4Cot7d0kOXpFMtlkKglJLKrQ2pULDvGYJ2WxbCcsD2iRwc95/v5cOYue7SMyC65jW3I1YCx/qO2ntuiXDljFPRvz5CZwIe4CwrhmMMwzEdZdnwzAKICfNgKTSUQizZXkQcCCEpYKKPU8ceqx2Z96cpmngH1Z0MhGyNCPzJ8tmFaFPrl9C0esRiOnfvFsl+LexCrpt8/YxDLKSo2qn/jqmtCPt/oGftBILPKyuezOP2tm9fpbfskAMYvdP0OMKNhV+L68ElHHx2QwSZwOtwfrKddQpgdOsoNAr1hYwwX4nt58r5oU0TQUIaJmUYCxkwuwdk8RLsEdQ8BO42ksnAR5YcmGSrkHLcw1G0jlC530oO/9I4DCcQSlFCkimWV3mL0zstlkTYXpD1sqQmagmUEsuP197F6MyokJutyJG5zeUbA2YRkzX+W2/nmgcpMcQ3jteWXW7z6jyWibfW7AWWwT7Ar/DDbZEneQS2moWTQGmTJfmxX9b/4cqsY7kA=
  - secure: HAhTMlCmWwtrIiSZ5jgE32SAavsN96ms83uE3zpcnH/Gkg67IXhkNDgyOWuZo6oBy7AokMRq9MdkZHkFiRDhNBuqDEWPkkzi9m3oMhTMxM+iaRw4HPFcf9dmXLPBEPeY5UTD6GAMWwahMSCcrVs8ShLYlffNU22duYElD/L44bcJW4muHLlX7PVXWuGX6yZuVyrHI2WUEXSHutxLXtV+5heJncMGmA74aNO3bo3HiXeaK1A42HXT6YsmDh2BmHXleILGaIbtNgPtL7xdD/+SuxtdpMNEMQHvr3v/v93rziZWdsAWBjKMx74AYJSaet0MgMm/w6y+lbO7+MNARin43eGWhNPNjyANsTwzv4m48NITPBSA37htEZ79JoJKjNSUfPXP/w1znQ9tJrqVtrHcK6k/+Xk8SgN/ZFQ1uVJPCe/yOGteTPqxHV7hRLNoKYeMXuAn3h36GloTKoPuGy6zB9zJvhT0ckcciBJQbHDQRIS/6hcEjOd4akOhf3vc/msa1Dk3oKB8OAJwnnTgvnE/IFJek+wf4RTHBd6pFAoQx26l3xNtq2Gdwbu0cPbmmVoYO5DVc5dbmU72cNVI8+FdUuqZg0eFWh1Mg8+nNXvq29STEKkJU4obFlyZVXm1LzWYqFYBpFzrWlQtGUehUDi9k+0TQAUIB7cog79rgubyIzU=
  - secure: ow+iSZqRBN1z6XvOm/9Zhp4gZdVIpSLqROMfLTrpcpN0PTtH2F+JwQZIno4r2ol5+Ut39doaVqDKZ1Kw9L+BW7atTWFbAWGYaAFKwEkc9z9OogPkNX+1xwfxie6/V7w9uyNTiDptU3mzAnJvBwYtJRl7nZeiN0tIPEsi6K7v85ce/OC5Yqt3U9mBK1y/THyxXohR3WKNdUcwHDggoVdmTMuBWPo5KixoanJNNcXmSGhDuSGGDhzbPAO4ejNfmbGm4QfxXQcfI51mXN+7kU+GJaYJlPyjI3vY+0T/8d7xpHz+D2H0IcWJTnoBWAC0SlVbOBdy0dm5ioskh5FvrEF4OZmkWZ+aNISOhyBFFOpHpHPK8hKwfwI807uDnzStFeWDKe4KgPqfGbYLPA+70XS1pis11vV1jVwJzb3JsMWAzg4KGPXfkTBWWxG/OTn97zpg+JYMxuNYGa2aQ6W24M4JdSi/7TxnyZtf6jyTJp8wyh+K9rDB8dcDblZmdnc6DMAK7pbwtIa9g5fV0WyaFQbroxcHFA7BumT6Wlce8+7IfuMQxbu6YMqIe64HQR6M3JxEvC2uec3myDX5zYny8iZd76JLEk7yyFyDwaVSbzKi9+nOkO2T9C9gzaZ7CpVONM5HPUBCUVKm5m578N0D0eAlbreMY49ccyZZURuZG3WGlhE=
